apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: ga-negocio
    options:
      disableNameSuffixHash: true
      immutable: false
    namespace: gpa-sso-int
    envs:
      - ./ga-negocio.env